name: Docker Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag daseeds/docker-react-test:$(date +%s)
    - name: Run tests
      run: docker run -e CI=true daseeds/docker-react-test
